# Generated by Django 3.2.6 on 2021-08-26 01:10

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.Field(verbose_name=django.contrib.auth.models.User)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.Field(verbose_name=django.contrib.auth.models.User)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('bio', models.Field(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['user'],
            },
        ),
    ]
