# Generated by Django 3.2.6 on 2021-09-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_auto_20210907_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
