# Generated by Django 3.2.6 on 2021-09-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_alter_thread_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
